FROM python:3.11

WORKDIR /app

COPY requirements.txt ./

RUN pip install -r requirements.txt

COPY wait-for-it.sh /usr/local/bin/wait-for-it.sh

RUN chmod +x /usr/local/bin/wait-for-it.sh


COPY . .


CMD ["sh", "-c", "wait-for-it.sh api:2222 -- wait-for-it.sh db:3306 -- python main.py"]
