version: '3'

services:
  
  privoxy:
    image: dockage/tor-privoxy:latest
    restart: always

  db:
    image: mysql:latest
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456789010
      - MYSQL_USER=botuser
      - MYSQL_DATABASE=botdb
      - MYSQL_PASSWORD=123456789010

  discord_bot:
    build: "./discord_bot"
    environment:
      - proxy=http://privoxy:8118 #leave as it is
      - api_url=http://api:2222 #leave as it is
      - TOKEN=MTI1MzE1MjkzODU0NTY0NzYxNg.G0Pu8_.X4e8Yks79f8yE5hmRkdlt-ntqAx42s-ZVPKvJs #YOUR BOT TOKEN
      - MYSQL_URL=mysql+pymysql://botuser:123456789010@db:3306/botdb
      - time_between_checks=15
      - my_ip=185.182.185.42 # YOUR SERVER IP

    depends_on:
      - api
      - privoxy
      - db

  api:
    build: "./api"
    environment:
      - my_ip=185.182.185.42
      - proxy=http://privoxy:8118

    ports:
      - 2222:2222
    depends_on:
      - privoxy
      - db  
volumes:
  mysql-data:
