# Generated by Django 5.0.7 on 2024-07-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article',
            field=models.TextField(null=True),
        ),
    ]
