FROM python:3.11



RUN useradd -ms /bin/bash api
USER api
WORKDIR /home/api/src

COPY requirements.txt ./

RUN pip install -r requirements.txt

COPY . .

EXPOSE 2222

#CMD ["service","tor","status"]
CMD ["python3","api.py"]
